version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - ./gradlew clean
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/TeaTimeJar.jar
  discard-paths: yes